version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: siriustools-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./backend/.env:/app/.env:ro

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: siriustools-frontend
    restart: unless-stopped
    ports:
      - '5173:80'
    depends_on:
      - backend
